# Generated by Django 4.2.15 on 2024-09-18 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violation_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentviolation',
            name='remarks',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade_level',
            field=models.CharField(choices=[('SHS11', 'Grade 11'), ('SHS12', 'Grade 12'), ('COLG1', 'First Year College'), ('COLG2', 'Second Year College'), ('COLG3', 'Third Year College'), ('COLG4', 'Fourth Year College')], max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_student_id', message='Please input a valid student ID in the format 20XX-XXXXXX', regex='20[0-9]{2}-[0-9]{6}')]),
        ),
    ]
