# Generated by Django 4.2.15 on 2024-09-21 19:17

from django.db import migrations, models
import django.db.models.deletion
import violation_tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('violation_tracker', '0002_studentviolation_remarks_alter_student_grade_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentviolation',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StudentViolationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=violation_tracker.models.student_violation_file_path)),
                ('student_violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violation_files', to='violation_tracker.studentviolation')),
            ],
        ),
    ]
