# Generated by Django 4.2.15 on 2024-09-27 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violation_tracker', '0004_studentviolation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentviolation',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 28, 2, 3, 14, 787130)),
        ),
    ]
