# Generated by Django 4.2.15 on 2024-08-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violation_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='violation_list',
            field=models.ManyToManyField(blank=True, related_name='student_violations', to='violation_tracker.violation'),
        ),
    ]
