# Generated by Django 4.2.15 on 2024-08-22 17:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('violation_tracker', '0002_violation_student_violation_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='violation_list',
        ),
        migrations.CreateModel(
            name='StudentViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offense_count', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('category', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='violation_tracker.student')),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='violation_tracker.violation')),
            ],
        ),
    ]
