# Generated by Django 4.2.15 on 2024-08-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violation_tracker', '0003_remove_student_violation_list_studentviolation'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='violation_class',
            field=models.CharField(choices=[('Minor', 'Minor'), ('Major', 'Major')], default='Minor', max_length=200),
        ),
    ]
