# Generated by Django 4.2.15 on 2024-09-02 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violation_tracker', '0006_alter_student_enrollment_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_year',
            field=models.IntegerField(default='2021', validators=[django.core.validators.MaxValueValidator(2024), django.core.validators.MinValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='2021-77667', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_student_id', message='Please input a valid student ID in the format 20XX-XXXXXX', regex='20[0-9]{2}-[0-9]{6}')]),
        ),
    ]
