# Generated by Django 4.2.15 on 2024-09-02 15:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('student_id', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_student_id', message='Please input a valid student ID in the format 20XX-XXXXXX', regex='20[0-9]{2}-[0-9]{6}')])),
                ('enrollment_year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2024), django.core.validators.MinValueValidator(2000)])),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('violation_class', models.CharField(choices=[('Minor', 'Minor'), ('Major', 'Major')], default='Minor', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StudentViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offense_count', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('category', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='violation_tracker.student')),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='violation_tracker.violation')),
            ],
        ),
    ]
