# Generated by Django 4.2.15 on 2024-09-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violation_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('SHS11', 'Grade 11'), ('SHS12', 'Grade 12'), ('COLG1', 'First Year College'), ('COLG2', 'Second Year College'), ('COLG3', 'Third Year College'), ('COLG4', 'Fourth Year College')], max_length=200),
        ),
    ]
