# Generated by Django 4.2.15 on 2024-09-04 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('violation_tracker', '0005_alter_student_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
    ]
